fechatupla1 = (25, 12, 2016)
print("Imprimimos la primer tupla")
print(fechatupla1)
fechalista = list(fechatupla1)
print("Imprimimos la lista que se le copio la tupla anterior")
print(fechalista)
fechalista[0] = 31
print("Imprimimos la lista ya modificada")
print(fechalista)
fechatupla2 = tuple(fechalista)
print("Imprimimos la segunda tupla que se le copio la lista")
print(fechatupla2)
